import type { Metadata } from "next";
// 1. Importe la nouvelle police
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { NavBar } from "@/components/nav-bar";
import QueryProvider from "./provider/queryProvider";

// 2. Configure la police (tu peux retirer geistSans et geistMono)
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      {/* 3. Applique la variable et la classe de police ici */}
      <body className={`${inter.variable} font-sans antialiased`}>
        <SidebarProvider>
          <TooltipProvider>
            <AppSidebar />
            <main className="w-full h-[100vh] overflow-hidden">
              <NavBar />
              <QueryProvider>
                {children}
              </QueryProvider>
            </main>
          </TooltipProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}